close #317 make use of the API to get search data
code4romania/seismic-risc pull request #511
Opened 2021-01-30 14:35 UTC by vladplesu

### What does it fix?

Added necessary components and handlers to make use of the API to get search data.
This will work only when all seismic categories option is selected. If one of the other seismic categories option is selected the search will look through all the buildings, but the markers for the buildings might be hidded. I see a two options here:

- when searching the app will switch by default to all seismic categories option and show all results.
- the app will look through all the buildings, but filter the results to show only the buildings matching the currently selected seismic category option.

Let me know what you think.

[![Image from Gyazo](https://i.gyazo.com/0ed9c3249260e41424ede0fc8d078d66.gif)](https://gyazo.com/0ed9c3249260e41424ede0fc8d078d66)

Closes #317

- Add context provider.
- Add reducer.
- Add search handlers in SearchFragment component.
- Add SearchResults component to show results.

### How has it been tested?

**If server can't be reached.**

[![Image from Gyazo](https://i.gyazo.com/df964ef5d03d63e6b814cb8bb92336c1.gif)](https://gyazo.com/df964ef5d03d63e6b814cb8bb92336c1)

**If no results found.**

[![Image from Gyazo](https://i.gyazo.com/0e9c0f43ebf0bd88d9f8ea5c043f85d4.gif)](https://gyazo.com/0e9c0f43ebf0bd88d9f8ea5c043f85d4)

**If results found.**

[![Image from Gyazo](https://i.gyazo.com/6313166626eb689d9ecef0ba4da9da81.gif)](https://gyazo.com/6313166626eb689d9ecef0ba4da9da81)

**If drawer close button is clicked.**

[![Image from Gyazo](https://i.gyazo.com/384cb93675fa9a7961dd0cec773c48f7.gif)](https://gyazo.com/384cb93675fa9a7961dd0cec773c48f7)

**If search result is clicked.**
[![Image from Gyazo](https://i.gyazo.com/dbacf3e1387699b3cce44f680f7682d3.gif)](https://gyazo.com/dbacf3e1387699b3cce44f680f7682d3)

2021-02-03 09:31 UTC, surdu commented on client/src/context.js
> +export { AppContext, AppProvider };
Do we need to export AppContext if we export the useGlobalContext ?

2021-02-03 09:32 UTC, surdu requested changes

2021-02-03 09:32 UTC, surdu commented on client/src/reducer.js
> +        searchError: `Nu a fost gasita nici o cladire cu adresa "${action.payload}."`,
```suggestion
        searchError: `Nu a fost gasită nici o clădire cu adresa "${action.payload}."`,
```

2021-02-06 10:18 UTC, tudoramariei approved these changes

2021-02-06 10:42 UTC, merged