Clustering for markers
code4romania/seismic-risc pull request #567
Opened 2021-02-25 19:26 UTC by annacs94

### What does it fix?

Closes #547 

### How has it been tested?
- manually with the large dataset; unit tests to be added

2021-03-01 15:12 UTC, bertearazvan requested changes
Arata super bine! 🎈 Good job!! Sorry if I got too picky here and there

Am mai observat un mic detaliu si anume daca dau click pe un cluster care e mai zoomed in iar apoi apas pe unul din markers, ma duce pe un zoom mai mic si trebuie sa apas din nou pe cluster ca sa vad markerele din acel cluster and so on (exemplu: `Strada POPA TATU`). 

Un quick fix pentru a rezolva asta ar fi ca atunci cand apesi pe un marker, zoom-ul sa fie mai mare fata de cat e setat sa se duca acum. (Probably related to #544). Insa ar putea fi facut cum scrie in issue 👍🏼 

Lemme know if you have any questions 💯

2021-03-01 15:12 UTC, bertearazvan commented on client/src/hooks/map/ClusterLayerBuilder.js
> +    const svgMarkup =
And you can add some formatting and indentation to that HTML, even if it's just a string, it makes it easier to read.

2021-03-01 15:48 UTC, annacs94 commented on client/src/components/HereMapInteractive/HereMapInteractive.js
> +        <h1>Here Maps API Key not set</h1>
This was not my code initially, that's why I would ask @tudoramariei. Can we get rid of the alt text and simply not display the map if there is no API key set?

2021-03-01 17:20 UTC, tudoramariei commented on client/src/components/HereMapInteractive/HereMapInteractive.js
> +        <h1>Here Maps API Key not set</h1>
Yeah, it should be fine getting rid of the text at this point 🤔

2021-03-01 17:27 UTC, annacs94 commented
> Arata super bine! 🎈 Good job!! Sorry if I got too picky here and there
> 
> Am mai observat un mic detaliu si anume daca dau click pe un cluster care e mai zoomed in iar apoi apas pe unul din markers, ma duce pe un zoom mai mic si trebuie sa apas din nou pe cluster ca sa vad markerele din acel cluster and so on (exemplu: `Strada POPA TATU`).
> 
> Un quick fix pentru a rezolva asta ar fi ca atunci cand apesi pe un marker, zoom-ul sa fie mai mare fata de cat e setat sa se duca acum. (Probably related to #544). Insa ar putea fi facut cum scrie in issue 👍🏼
> 
> Lemme know if you have any questions 💯

@bertearazvan Thanks :) I have pushed the fixes. 
Also, the fix is ready for #544, și rezolvă problema pe care ai descris-o. Aș face un PR după acest branch ajunge în develop.

2021-03-01 17:31 UTC, annacs94 commented on client/src/components/HereMapInteractive/HereMapInteractive.js
> +      {apikey ? (
Not in production... Dar un developer nu-l va seta neapărat.

2021-03-02 07:11 UTC, tudoramariei approved these changes

2021-03-02 07:33 UTC, merged